// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9viiJOK25UT3xuLTzD89WxjW-NJXamFQ',
    appId: '1:911715201343:web:2be923fb4957db5317e38a',
    messagingSenderId: '911715201343',
    projectId: 'medi-flutter',
    authDomain: 'medi-flutter.firebaseapp.com',
    storageBucket: 'medi-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcBib2Ab7vcapPhEOESysPh39cS_fRgvo',
    appId: '1:911715201343:android:25612e895991168b17e38a',
    messagingSenderId: '911715201343',
    projectId: 'medi-flutter',
    storageBucket: 'medi-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv6e2FJ3RnDrTUl-U3NnE3IgWLC7eTPGo',
    appId: '1:911715201343:ios:cf50388650341c4e17e38a',
    messagingSenderId: '911715201343',
    projectId: 'medi-flutter',
    storageBucket: 'medi-flutter.firebasestorage.app',
    iosBundleId: 'com.medi.flutterAppMedi',
  );

}